```{r}
library(RmarineHeatWaves)
library(ggplot2)
```

```{r}
ts <- make_whole(sst_WA)
mhw <- detect(ts,
  climatology_start = "1983-01-01",
  climatology_end = "2012-12-31"
)

mhw$event %>%
  dplyr::ungroup() %>%
  dplyr::select(event_no, duration, date_start, date_peak, int_mean, int_max, int_cum) %>%
  dplyr::arrange(-int_cum) %>%
  head(5)
```

```{r}
event_line(mhw,
  spread = 200, metric = "int_cum",
  start_date = "2010-10-01", end_date = "2011-08-30"
)
```


```{r}
mcs2 <- mcs$clim
mcs2 <- mcs2[2990:3190,]

# # Note that the plot centres on the polygons, so it may be necessary to manually zoom out a bit
ggplot(data = mcs2, aes(x = t)) +
  geom_flame(aes(y = thresh_clim_year, y2 = temp), fill = "steelblue3", show.legend = F) +
  geom_line(aes(y = temp, colour = "temp")) +
  geom_line(aes(y = thresh_clim_year, colour = "thresh"), size = 1.0) +
  geom_line(aes(y = seas_clim_year, colour = "seas"), size = 1.2) +
  scale_colour_manual(name = "Line Colour",
                      values = c("temp" = "black", "thresh" =  "forestgreen", "seas" = "grey80")) +
  scale_y_continuous(limits = c(18, 23.5)) +
  xlab("Date") +
  ylab(expression(paste("Temperature [", degree, "C]")))

ggplot(mcs$event, aes(x = date_start, y = int_cum)) +
  geom_lolli(colour = "steelblue3", colour.n = "navy", n = 7) +
  xlab("Date") +
  ylab(expression(paste("Cumulative intensity [days x ", degree, "C]")))
```


```{r}
Ipaper::set_font()

p <- coldwave_flame(data)
write_fig(p, 'd:/Rplot.pdf', 10, 5)
```
